//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Перелет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Перелет()
        {
            this.Тур = new HashSet<Тур>();
            this.Тур1 = new HashSet<Тур>();
        }
    
        public int id { get; set; }
        public int Авиакомпании_id { get; set; }
        public int Цена_Компании { get; set; }
        public int Цена_Клиента { get; set; }
        public int Страна_Отправления_id { get; set; }
        public int Пункт_Назначения_id { get; set; }
    
        public virtual Авиакомпании Авиакомпании { get; set; }
        public virtual Страна Страна { get; set; }
        public virtual Страна Страна1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тур> Тур { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тур> Тур1 { get; set; }
    }
}
