//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тур
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тур()
        {
            this.Договор = new HashSet<Договор>();
        }
    
        public int id { get; set; }
        public int Отель_id { get; set; }
        public int Страна_id { get; set; }
        public int Авиарейса_Вылета_id { get; set; }
        public int Авиарейса_Прилёта_id { get; set; }
        public System.DateTime Дата_Начала { get; set; }
        public System.DateTime Дата_Окончания { get; set; }
        public int Стоимость_Услуг_Компании { get; set; }
        public int Количество_Свободных_Мест { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор> Договор { get; set; }
        public virtual Отель Отель { get; set; }
        public virtual Перелет Перелет { get; set; }
        public virtual Перелет Перелет1 { get; set; }
        public virtual Страна Страна { get; set; }
    }
}
